In [1]:
import pyarrow as pa
import pyarrow.parquet as pq
import os
import sys

In [2]:
table = pq.read_table('/home/njagz/Documents/FInal_Projects/data/input/green/year=2022/month=01/data.parquet')
df_green = table.to_pandas()

In [3]:
table = pq.read_table('/home/njagz/Documents/FInal_Projects/data/input/yellow/year=2022/month=01/data.parquet')
df_yellow = table.to_pandas()

In [4]:
df_green.head(10)

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,year,month
0,2,2022-01-01 00:14:21,2022-01-01 00:15:33,N,1.0,42,42,1.0,0.44,3.5,...,0.00,0.0,None,0.3,4.80,2.0,1.0,0.00,2022,1
1,1,2022-01-01 00:20:55,2022-01-01 00:29:38,N,1.0,116,41,1.0,2.10,9.5,...,0.00,0.0,None,0.3,10.80,2.0,1.0,0.00,2022,1
2,1,2022-01-01 00:57:02,2022-01-01 01:13:14,N,1.0,41,140,1.0,3.70,14.5,...,4.60,0.0,None,0.3,23.15,1.0,1.0,2.75,2022,1
3,2,2022-01-01 00:07:42,2022-01-01 00:15:57,N,1.0,181,181,1.0,1.69,8.0,...,0.00,0.0,None,0.3,9.30,2.0,1.0,0.00,2022,1
4,2,2022-01-01 00:07:50,2022-01-01 00:28:52,N,1.0,33,170,1.0,6.26,22.0,...,5.21,0.0,None,0.3,31.26,1.0,1.0,2.75,2022,1
5,1,2022-01-01 00:47:57,2022-01-01 00:54:09,N,1.0,150,210,1.0,1.30,7.0,...,0.00,0.0,None,0.3,8.30,2.0,1.0,0.00,2022,1
6,2,2022-01-01 00:13:38,2022-01-01 00:33:50,N,1.0,66,67,1.0,6.47,22.5,...,0.00,0.0,None,0.3,23.80,2.0,1.0,0.00,2022,1
7,2,2022-01-01 00:43:00,2022-01-01 00:49:20,N,1.0,40,195,1.0,1.15,6.0,...,0.00,0.0,None,0.3,7.30,2.0,1.0,0.00,2022,1
8,2,2022-01-01 00:41:04,2022-01-01 00:47:04,N,1.0,112,80,1.0,1.30,6.0,...,0.00,0.0,None,0.3,7.30,2.0,1.0,0.00,2022,1
9,2,2022-01-01 00:51:07,2022-01-01 01:09:31,N,1.0,256,186,1.0,4.75,17.0,...,4.21,0.0,None,0.3,25.26,1.0,1.0,2.75,2022,1

In [5]:
df_green.info()

<class 'pandas.DataFrame'>
RangeIndex: 62495 entries, 0 to 62494
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               62495 non-null  int64
 1   lpep_pickup_datetime   62495 non-null  datetime64[us]
 2   lpep_dropoff_datetime  62495 non-null  datetime64[us]
 3   store_and_fwd_flag     56200 non-null  str
 4   RatecodeID             56200 non-null  float64
 5   PULocationID           62495 non-null  int64
 6   DOLocationID           62495 non-null  int64
 7   passenger_count        56200 non-null  float64
 8   trip_distance          62495 non-null  float64
 9   fare_amount            62495 non-null  float64
 10  extra                  62495 non-null  float64
 11  mta_tax                62495 non-null  float64
 12  tip_amount             62495 non-null  float64
 13  tolls_amount           62495 non-null  float64
 14  ehail_fee              0 non-null      object
 15  improvement_surcharge  62495 non-null  float64
 16  total_amount           62495 non-null  float64
 17  payment_type           56200 non-null  float64
 18  trip_type              56200 non-null  float64
 19  congestion_surcharge   56200 non-null  float64
 20  year                   62495 non-null  category
 21  month                  62495 non-null  category
dtypes: category(2), datetime64[us](2), float64(13), int64(3), object(1), str(1)
memory usage: 9.7+ MB

In [6]:
df_green.isnull().sum()

VendorID                     0
lpep_pickup_datetime         0
lpep_dropoff_datetime        0
store_and_fwd_flag        6295
RatecodeID                6295
PULocationID                 0
DOLocationID                 0
passenger_count           6295
trip_distance                0
fare_amount                  0
extra                        0
mta_tax                      0
tip_amount                   0
tolls_amount                 0
ehail_fee                62495
improvement_surcharge        0
total_amount                 0
payment_type              6295
trip_type                 6295
congestion_surcharge      6295
year                         0
month                        0
dtype: int64

In [7]:
df_green[[
       'tip_amount', 'tolls_amount', 'ehail_fee', 'improvement_surcharge',
       'total_amount', 'payment_type', 'trip_type', 'congestion_surcharge',
       'year', 'month']].head(20)

,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,year,month
0,0.00,0.00,None,0.3,4.80,2.0,1.0,0.00,2022,1
1,0.00,0.00,None,0.3,10.80,2.0,1.0,0.00,2022,1
2,4.60,0.00,None,0.3,23.15,1.0,1.0,2.75,2022,1
3,0.00,0.00,None,0.3,9.30,2.0,1.0,0.00,2022,1
4,5.21,0.00,None,0.3,31.26,1.0,1.0,2.75,2022,1
5,0.00,0.00,None,0.3,8.30,2.0,1.0,0.00,2022,1
6,0.00,0.00,None,0.3,23.80,2.0,1.0,0.00,2022,1
7,0.00,0.00,None,0.3,7.30,2.0,1.0,0.00,2022,1
8,0.00,0.00,None,0.3,7.30,2.0,1.0,0.00,2022,1
9,4.21,0.00,None,0.3,25.26,1.0,1.0,2.75,2022,1
10,1.50,0.00,None,0.3,24.05,1.0,1.0,2.75,2022,1
11,0.00,0.00,None,0.3,13.80,2.0,1.0,0.00,2022,1
12,1.45,0.00,None,0.3,7.25,1.0,1.0,0.00,2022,1
13,0.00,6.55,None,0.3,25.35,2.0,1.0,0.00,2022,1
14,6.11,0.00,None,0.3,36.66,1.0,1.0,2.75,2022,1
15,0.00,0.00,None,0.3,5.80,3.0,1.0,0.00,2022,1
16,0.00,0.00,None,0.3,22.80,1.0,1.0,0.00,2022,1
17,0.00,0.00,None,0.3,20.30,2.0,2.0,0.00,2022,1
18,0.00,0.00,None,0.3,8.30,2.0,1.0,0.00,2022,1
19,0.00,0.00,None,0.3,25.30,2.0,2.0,0.00,2022,1

In [8]:
df_yellow.info()

<class 'pandas.DataFrame'>
RangeIndex: 2463931 entries, 0 to 2463930
Data columns (total 21 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
 19  year                   category
 20  month                  category
dtypes: category(2), datetime64[us](2), float64(12), int64(4), str(1)
memory usage: 364.4 MB

In [9]:
df_yellow.isnull().sum()

VendorID                     0
tpep_pickup_datetime         0
tpep_dropoff_datetime        0
passenger_count          71503
trip_distance                0
RatecodeID               71503
store_and_fwd_flag       71503
PULocationID                 0
DOLocationID                 0
payment_type                 0
fare_amount                  0
extra                        0
mta_tax                      0
tip_amount                   0
tolls_amount                 0
improvement_surcharge        0
total_amount                 0
congestion_surcharge     71503
airport_fee              71503
year                         0
month                        0
dtype: int64

In [10]:
df_yellow.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,year,month
0,1,2022-01-01 00:35:40,2022-01-01 00:53:29,2.0,3.80,1.0,N,142,236,1,...,3.0,0.5,3.65,0.00,0.3,21.95,2.5,0.0,2022,1
1,1,2022-01-01 00:33:43,2022-01-01 00:42:07,1.0,2.10,1.0,N,236,42,1,...,0.5,0.5,4.00,0.00,0.3,13.30,0.0,0.0,2022,1
2,2,2022-01-01 00:53:21,2022-01-01 01:02:19,1.0,0.97,1.0,N,166,166,1,...,0.5,0.5,1.76,0.00,0.3,10.56,0.0,0.0,2022,1
3,2,2022-01-01 00:25:21,2022-01-01 00:35:23,1.0,1.09,1.0,N,114,68,2,...,0.5,0.5,0.00,0.00,0.3,11.80,2.5,0.0,2022,1
4,2,2022-01-01 00:36:48,2022-01-01 01:14:20,1.0,4.30,1.0,N,68,163,1,...,0.5,0.5,3.00,0.00,0.3,30.30,2.5,0.0,2022,1
5,1,2022-01-01 00:40:15,2022-01-01 01:09:48,1.0,10.30,1.0,N,138,161,1,...,3.0,0.5,13.00,6.55,0.3,56.35,2.5,0.0,2022,1
6,2,2022-01-01 00:20:50,2022-01-01 00:34:58,1.0,5.07,1.0,N,233,87,1,...,0.5,0.5,5.20,0.00,0.3,26.00,2.5,0.0,2022,1
7,2,2022-01-01 00:13:04,2022-01-01 00:22:45,1.0,2.02,1.0,N,238,152,2,...,0.5,0.5,0.00,0.00,0.3,12.80,2.5,0.0,2022,1
8,2,2022-01-01 00:30:02,2022-01-01 00:44:49,1.0,2.71,1.0,N,166,236,1,...,0.5,0.5,2.25,0.00,0.3,18.05,2.5,0.0,2022,1
9,2,2022-01-01 00:48:52,2022-01-01 00:53:28,1.0,0.78,1.0,N,236,141,2,...,0.5,0.5,0.00,0.00,0.3,8.80,2.5,0.0,2022,1

In [11]:
df_yellow['fare_amount'].head(20)

0     14.5
1      8.0
2      7.5
3      8.0
4     23.5
5     33.0
6     17.0
7      9.0
8     12.0
9      5.0
10     8.5
11     4.5
12     4.5
13    11.5
14     7.5
15     8.0
16    14.0
17     9.5
18     5.0
19    13.0
Name: fare_amount, dtype: float64

In [12]:
df_yellow.info()

<class 'pandas.DataFrame'>
RangeIndex: 2463931 entries, 0 to 2463930
Data columns (total 21 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
 19  year                   category
 20  month                  category
dtypes: category(2), datetime64[us](2), float64(12), int64(4), str(1)
memory usage: 364.4 MB

In [13]:
df_green.info()

<class 'pandas.DataFrame'>
RangeIndex: 62495 entries, 0 to 62494
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               62495 non-null  int64
 1   lpep_pickup_datetime   62495 non-null  datetime64[us]
 2   lpep_dropoff_datetime  62495 non-null  datetime64[us]
 3   store_and_fwd_flag     56200 non-null  str
 4   RatecodeID             56200 non-null  float64
 5   PULocationID           62495 non-null  int64
 6   DOLocationID           62495 non-null  int64
 7   passenger_count        56200 non-null  float64
 8   trip_distance          62495 non-null  float64
 9   fare_amount            62495 non-null  float64
 10  extra                  62495 non-null  float64
 11  mta_tax                62495 non-null  float64
 12  tip_amount             62495 non-null  float64
 13  tolls_amount           62495 non-null  float64
 14  ehail_fee              0 non-null      object
 15  improvement_surcharge  62495 non-null  float64
 16  total_amount           62495 non-null  float64
 17  payment_type           56200 non-null  float64
 18  trip_type              56200 non-null  float64
 19  congestion_surcharge   56200 non-null  float64
 20  year                   62495 non-null  category
 21  month                  62495 non-null  category
dtypes: category(2), datetime64[us](2), float64(13), int64(3), object(1), str(1)
memory usage: 9.7+ MB

In [14]:
%pip install pyspark pyarrow==22.0.0

Requirement already satisfied: pyspark in /home/njagz/Documents/FInal_Projects/venv/lib/python3.12/site-packages (4.1.1)
Requirement already satisfied: pyarrow==22.0.0 in /home/njagz/Documents/FInal_Projects/venv/lib/python3.12/site-packages (22.0.0)
Requirement already satisfied: py4j<0.10.9.10,>=0.10.9.7 in /home/njagz/Documents/FInal_Projects/venv/lib/python3.12/site-packages (from pyspark) (0.10.9.9)
Note: you may need to restart the kernel to use updated packages.

In [15]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col, lit, year, month,
    to_timestamp, unix_timestamp
)

spark = SparkSession.builder \
    .appName("Taxi Silver Layer") \
    .getOrCreate()

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
26/03/02 21:51:50 WARN Utils: Your hostname, njagz-VMware-Virtual-Platform, resolves to a loopback address: 127.0.1.1; using 192.168.131.128 instead (on interface ens33)
26/03/02 21:51:50 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/03/02 21:51:52 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [16]:
df_yellow = spark.read.parquet("/home/njagz/Documents/FInal_Projects/data/input/yellow/year=2022/month=01/data.parquet")
df_green = spark.read.parquet("/home/njagz/Documents/FInal_Projects/data/input/green/year=2022/month=01/data.parquet")

In [17]:
# Transformations for Yellow Taxi Data
yellow_transformed = df_yellow.withColumnRenamed("tpep_pickup_datetime", "pickup_datetime") \
    .withColumnRenamed("tpep_dropoff_datetime", "dropoff_datetime") \
    .withColumn("service_type", lit("yellow")) \
    .withColumn("RatecodeID", col("RatecodeID").cast("integer")) \
    .withColumn("passenger_count", col("passenger_count").cast("integer"))  \
    .withColumn("trip_type", lit(0))  # Assuming trip_type is 0 for yellow taxis

# Transformations for Green Taxi Data
green_transformed = df_green.withColumnRenamed("lpep_pickup_datetime", "pickup_datetime") \
    .withColumnRenamed("lpep_dropoff_datetime", "dropoff_datetime") \
    .withColumn("service_type", lit("green")) \
    .drop("ehail_fee") \
    .withColumn("RatecodeID", col("RatecodeID").cast("integer")) \
    .withColumn("passenger_count", col("passenger_count").cast("integer")) \
    .withColumn("trip_type", col("trip_type").cast("integer")) \
    .withColumn("payment_type", col("payment_type").cast("integer")) \
    .withColumn("airport_fee", lit(0.00))  # Assuming airpot_fee is 0 for green taxis

In [18]:
set(yellow_transformed.columns) == set(green_transformed.columns)

True

In [20]:
yellow_transformed.printSchema()

root
 |-- VendorID: long (nullable = true)
 |-- pickup_datetime: timestamp_ntz (nullable = true)
 |-- dropoff_datetime: timestamp_ntz (nullable = true)
 |-- passenger_count: integer (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- RatecodeID: integer (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- PULocationID: long (nullable = true)
 |-- DOLocationID: long (nullable = true)
 |-- payment_type: long (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- congestion_surcharge: double (nullable = true)
 |-- airport_fee: double (nullable = true)
 |-- service_type: string (nullable = false)
 |-- trip_type: integer (nullable = false)

In [21]:
green_transformed.printSchema()

root
 |-- VendorID: long (nullable = true)
 |-- pickup_datetime: timestamp_ntz (nullable = true)
 |-- dropoff_datetime: timestamp_ntz (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- RatecodeID: integer (nullable = true)
 |-- PULocationID: long (nullable = true)
 |-- DOLocationID: long (nullable = true)
 |-- passenger_count: integer (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- payment_type: integer (nullable = true)
 |-- trip_type: integer (nullable = true)
 |-- congestion_surcharge: double (nullable = true)
 |-- service_type: string (nullable = false)
 |-- airport_fee: double (nullable = false)

In [25]:
green_transformed[['store_and_fwd_flag', 'RatecodeID','passenger_count','congestion_surcharge','payment_type','trip_type']].head(20)

[Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=0.0, payment_type=2, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=0.0, payment_type=2, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=2.75, payment_type=1, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=0.0, payment_type=2, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=2.75, payment_type=1, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=0.0, payment_type=2, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=0.0, payment_type=2, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=0.0, payment_type=2, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=0.0, payment_type=2, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=2.75, payment_type=1, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=2.75, payment_type=1, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=0.0, payment_type=2, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=0.0, payment_type=1, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=0.0, payment_type=2, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=2.75, payment_type=1, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=0.0, payment_type=3, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=0.0, payment_type=1, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=5, passenger_count=1, congestion_surcharge=0.0, payment_type=2, trip_type=2),
 Row(store_and_fwd_flag='N', RatecodeID=1, passenger_count=1, congestion_surcharge=0.0, payment_type=2, trip_type=1),
 Row(store_and_fwd_flag='N', RatecodeID=5, passenger_count=1, congestion_surcharge=0.0, payment_type=2, trip_type=2)]

In [31]:
from pyspark.sql.functions import col

green_transformed.filter(col('store_and_fwd_flag').isNull()).show()

+--------+---------------+----------------+------------------+----------+------------+------------+---------------+-------------+-----------+-----+-------+----------+------------+---------------------+------------+------------+---------+--------------------+------------+-----------+
|VendorID|pickup_datetime|dropoff_datetime|store_and_fwd_flag|RatecodeID|PULocationID|DOLocationID|passenger_count|trip_distance|fare_amount|extra|mta_tax|tip_amount|tolls_amount|improvement_surcharge|total_amount|payment_type|trip_type|congestion_surcharge|service_type|airport_fee|
+--------+---------------+----------------+------------------+----------+------------+------------+---------------+-------------+-----------+-----+-------+----------+------------+---------------------+------------+------------+---------+--------------------+------------+-----------+
+--------+---------------+----------------+------------------+----------+------------+------------+---------------+-------------+-----------+-----+-------+----------+------------+---------------------+------------+------------+---------+--------------------+------------+-----------+

In [28]:
yellow_transformed = yellow_transformed.fillna({
    "store_and_fwd_flag": "N",
    "RatecodeID": -1,
    "passenger_count": 1,
    "congestion_surcharge": 0.0,
    "airport_fee": 0.0
})

green_transformed = green_transformed.fillna({
    "store_and_fwd_flag": "N",
    "RatecodeID": 0,
    "passenger_count": 0,
    "congestion_surcharge": 0.0,
    "payment_type": 0,
    "trip_type": -1
})

In [29]:
def check_nulls(df):
    from pyspark.sql.functions import col, sum, when
    
    return df.select([
        sum(when(col(c).isNull(), 1).otherwise(0)).alias(c)
        for c in df.columns
    ])

In [30]:
check_nulls(yellow_transformed).show()
check_nulls(green_transformed).show()

+--------+---------------+----------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------+---------+
|VendorID|pickup_datetime|dropoff_datetime|passenger_count|trip_distance|RatecodeID|store_and_fwd_flag|PULocationID|DOLocationID|payment_type|fare_amount|extra|mta_tax|tip_amount|tolls_amount|improvement_surcharge|total_amount|congestion_surcharge|airport_fee|service_type|trip_type|
+--------+---------------+----------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------+---------+
|       0|              0|               0|              0|            0|         0|                 0|           0|           0|           0|          0|    0|      0|         0|           0|                    0|           0|                   0|          0|           0|        0|
+--------+---------------+----------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------+---------+

+--------+---------------+----------------+------------------+----------+------------+------------+---------------+-------------+-----------+-----+-------+----------+------------+---------------------+------------+------------+---------+--------------------+------------+-----------+
|VendorID|pickup_datetime|dropoff_datetime|store_and_fwd_flag|RatecodeID|PULocationID|DOLocationID|passenger_count|trip_distance|fare_amount|extra|mta_tax|tip_amount|tolls_amount|improvement_surcharge|total_amount|payment_type|trip_type|congestion_surcharge|service_type|airport_fee|
+--------+---------------+----------------+------------------+----------+------------+------------+---------------+-------------+-----------+-----+-------+----------+------------+---------------------+------------+------------+---------+--------------------+------------+-----------+
|       0|              0|               0|                 0|         0|           0|           0|              0|            0|          0|    0|      0|         0|           0|                    0|           0|           0|        0|                   0|           0|          0|
+--------+---------------+----------------+------------------+----------+------------+------------+---------------+-------------+-----------+-----+-------+----------+------------+---------------------+------------+------------+---------+--------------------+------------+-----------+